name: Release
on:
    workflow_dispatch: {}
    push:
        branches:
            - main

jobs:
    linting:
        uses: ./.github/workflows/linting.yml

    tests:
        uses: ./.github/workflows/tests.yml

    build:
        uses: ./.github/workflows/build.yml

    release:
        name: Release
        needs: [linting, tests, build]
        runs-on: macos-13

        permissions:
          contents: write
          issues: write
          pull-requests: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  # pulls all commits (needed for semantic release to correctly version)
                  fetch-depth: '0'
                  persist-credentials: false

            - name: Install Dependencies
              run: |
                bundle install
                npm install

            - name: GitHub Release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.DISTRIBUTION_CERTIFICATE_BASE64 }}
                DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSWORD }}
                KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
              run: npx semantic-release@21

            - name: Publish to CocoaPods
              env:
                COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
              run: bundle exec fastlane publish
