name: Release
on:
    workflow_dispatch: {}
    push:
        branches:
            - main

jobs:
    linting:
        uses: paypal/paypal-messages-ios/.github/workflows/linting.yml@release

    tests:
        uses: paypal/paypal-messages-ios/.github/workflows/tests.yml@release

    build:
      uses: paypal/paypal-messages-ios/.github/workflows/build.yml@release

    release:
        name: Release
        needs: [linting, tests, build]
        runs-on: macos-latest

        permissions:
          contents: write
          issues: write
          pull-requests: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  # pulls all commits (needed for semantic release to correctly version)
                  fetch-depth: '0'
                  persist-credentials: false

            - name: Install Dependencies
              run: |
                bundle install
                npm i -g @semantic-release/exec @semantic-release/changelog @semantic-release/git conventional-changelog-conventionalcommits@6.1.0

            - name: GitHub Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release@21

            - name: Publish to CocoaPods
              env:
                COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
              run: bundle exec fastlane publish
