name: Tests
on: [pull_request, workflow_dispatch, workflow_call]

concurrency:
  group: tests-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: bundle install

      - name: Run Unit Tests
        run: bundle exec fastlane tests summary:$GITHUB_STEP_SUMMARY
